name: target_sistemas
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_inappwebview: ^5.8.0
  page_transition: ^2.1.0
  url_launcher: ^6.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/target_logo.png