name: target_sistemas
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_inappwebview: ^5.8.0
  flutter_launcher_icons: ^0.13.1
  page_transition: ^2.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  mobx:
  flutter_mobx: ^2.1.1 
  auto_size_text: 

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: 
  mobx_codegen:

flutter:
  uses-material-design: true

  assets:
     - assets/images/target_logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/target_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true   

scripts:
  post-update: 
    - flutter pub run build_runner build --delete-conflicting-outputs
    